name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

permissions:
  contents: read

jobs:
  pip:
    environment: pypi
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install
      run: |
        pip install --upgrade pip wheel
        pip install build twine
    - name: Build
      run: |
        python -m build
        twine check dist/*
    - name: Publish packages to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
